language: ruby
cache: bundler
rvm:
- 2.6.2
env:
  secure: hQgWRJvjnS8M6upCfoWoO111KXuRF4mJb7HuC/fkAkvmSd4DGzvoHgIJZw+bo+tdAMj2H8EfImDlYi7lP4TPxzJrWgzcxM55XR8Coujc/vUdBeszPeniFiulhtk8TneN8YR2Izc1sD5neQTxXiMJSbbT4JXRhBfabYTxhBFpFLRXoG5u46IDJqJUm6qHY/gwH3fA9a+AjGWEE0s/rlsB4APQoAsEVGXPupCasrArO7ZnYOmpqeT9L3lyKq0EVYMMHKOWrcYLU8og1If32Q4pq36+IJvpHC6MYpg+fndWEOo2s2llNffnLR29JJJ8omUvOuttUHltU4RXwW56/xx/gC8zUrEMBhO8sUOinVAicGaA9faowRkgDrsh418I78wJn/h55F2g05AsPMNHRqRzk3LUqYPD9iCAm1FDvtgJMpJUB0RxVREHPXctVL4QUgWHxtY7aWxZeLIjMQuvVc9IaWBRwEDJjevnEpSI6Zhk0tC70efiUt73EhntutEmMu04yuYpvlRvDB7sF3HGry+HNUAGX1wTMBFkFW5bHSnSzs/2kUgoJMWY+u/eS/VXJK/vZUkreH40biD28o/sV3DtZC9jRSsTW8vQNRdX4zzI2NrKtosaaATBQAVdc1gEjTiDeLMNdjFrfM7WL7+MyK5onEy95xADvKbzWciYwsdbveM=
