default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= Rails.application.credentials.fetch(:database_host) %>
  port: <%= Rails.application.credentials.fetch(:database_port) %>
  username: <%= Rails.application.credentials.fetch(:database_username) %>
  password: <%= Rails.application.credentials.fetch(:database_password) %>

development:
  <<: *default
  database: <%= Rails.application.credentials.fetch(:database_name) %>_dev
test:
  <<: *default
  database: <%= Rails.application.credentials.fetch(:database_name) %>_test
production:
  <<: *default
  database: <%= Rails.application.credentials.fetch(:database_name) %>_prod
