name: Fly Deploy
on:
  push:
    branches:
      - master
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  ci-rake:
    uses: ./.github/workflows/ci-rake.yml
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: ci-rake
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
